services:
  db:
    image: mariadb
    restart: no
    secrets:
      - db_root_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_logs:/var/log/mysql
    networks:
      - ff-pugbot

  node:
    image: node:current-alpine
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - ff-pugbot
    command: npm run start

networks:
  ff-pugbot:
    driver: bridge

secrets:
   db_root_password:
     file: ./secrets/db_root_password.txt

volumes:
  mariadb_data:
  mariadb_logs:
  node_modules: